### PR TITLE
Generic pandoc tests

### PR DESCRIPTION
**Pull request by mpacer**
Not sure what is causing the merge conflict, but if you rebase on upstream/master the fix (which is pretty simple) should work to make tests pass.

### CODE REVIEW

**Comment by amueller** [comment]
I just rebased but the diff looks weird?

**Comment by mpacer** [comment]
I think its because I had rebased on master separately and I guess it is treating mine as the old one

**Comment by mpacer** [comment]
Ok so I'm also going to push the deprecation warnings.

**Comment by amueller** [comment]
ok sure. Hm I'm still getting the weird file not found errors...

**Comment by mpacer** [comment]
When I test it, it runs without issue. 

What OS are you working on?

**Comment by mpacer** [comment]
Also, are you running py.test --pyargs nbconvert from the root directory?

**Comment by amueller** [comment]
ubuntu. No, I was running `py.test .` Sorry I'm new to pytest...

**Comment by mpacer** [comment]
No problem! I'm new to pytest too. The only reason I knew to run it that way was because its in the README.

**Comment by amueller** [comment]
different color scheme, same error ;) Gotta grab lunch but I'll be back soon.

**Comment by mpacer** [comment]
When you test on master, do you get the same error?

**Comment by mpacer** [comment]
If you merge this, I'm pretty sure this will fix the travis build. 

Also, it'd help a lot if you were to allow edits from maintainers on your original PR.

I think that your error with the temp dir stuff might be a local environment thing, though I'm not sure. That's why my guess is that you'll run into the same error on master.

**Comment by mpacer** [comment]
Aha — you had allowed maintainer edits(thank you). I wish they'd surface whether or not someone has done that in the github UI.

**Pull request closed without merging**
